name: Build single extension

on:
  workflow_dispatch:
    inputs:
      lang:
        description: Extension language (en, ar, es, pt...)
        default: 'id'
        required: false
      extension:
        description: Target extension name
        required: true
      git-repo:
        description: Git repo (Optional, defaults to <your name>/aniyomi-extensions)
        default: 'SupKelelawar/extensions-source'
        required: false
      git-ref:
        description: Git Ref (Optional, defaults to master)
        default: 'main'
        required: false

env:
  EXTPATH: ${{ github.event.inputs.lang }}/${{ github.event.inputs.extension }}
  EXTSLUG: ${{ github.event.inputs.lang }}:${{ github.event.inputs.extension }}
  REPO: ${{ github.event.inputs.git-repo }}

jobs:
  build-extension:
    name: Build a single extension
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          set -e
          if [[ -z "${{ env.REPO }}" ]]; then
            echo "REPO=${{ github.repository_owner }}/aniyomi-extensions" >> $GITHUB_ENV
          fi

      - name: Clone Repository (Latest)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build APK
        env:
          CI: false
        run: ./gradlew -p src ${{ env.EXTSLUG }}:assembleDebug

      - name: Zip the APK
        run: |
          cd src/${{ env.EXTPATH }}/build/outputs/apk/debug
          zip -r ${{ github.event.inputs.lang }}-${{ github.event.inputs.extension }}.zip *.apk

      - name: Checkout target branch (where the zip will be extracted)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          ref: 'target-branch'  # Ganti dengan nama branch tujuan tempat ekstraksi file zip

      - name: Create directory for extracted APK files
        run: mkdir -p extracted_apk

      - name: Copy and Extract APK zip
        run: |
          cp src/${{ env.EXTPATH }}/build/outputs/apk/debug/${{ github.event.inputs.lang }}-${{ github.event.inputs.extension }}.zip extracted_apk/
          cd extracted_apk
          unzip ${{ github.event.inputs.lang }}-${{ github.event.inputs.extension }}.zip

      - name: Commit and push extracted files to target branch
        run: |
          git add extracted_apk/
          git commit -m "Add extracted APK files for ${{ github.event.inputs.lang }}-${{ github.event.inputs.extension }}"
          git push origin target-branch  # Push ke branch yang dituju
