name: Build single extension

on:
  workflow_dispatch:
    inputs:
      lang:
        description: Extension language (en, ar, es, pt...)
        required: true
      extension:
        description: Target extension name
        required: true
      is-multisrc:
        description: Is the extension multisrc?
        default: 'false'
        required: true
      git-repo:
        description: Git repo (Optional, defaults to <your name>/aniyomi-extensions)
        default: ''
        required: false
      git-ref:
        description: Git Ref (Optional, defaults to master)
        default: 'master'
        required: false

env:
  # Set environment variables for CI and extension path
  CI: true
  CI_MATRIX_LANG: ${{ github.event.inputs.lang }}
  CI_MULTISRC: ${{ github.event.inputs['is-multisrc'] }}

jobs:
  build-extension:
    name: Build a single extension
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          set -e
          if [[ -z "${{ github.event.inputs.git-repo }}" ]]; then
            echo "REPO=${{ github.repository_owner }}/aniyomi-extensions" >> $GITHUB_ENV
          else
            echo "REPO=${{ github.event.inputs.git-repo }}" >> $GITHUB_ENV
          fi

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: adopt

      - name: Build APK
        run: |
          # Determine whether the extension is from multisrc or individual
          if [[ "${{ env.CI_MULTISRC }}" == "true" ]]; then
            ./gradlew :extensions:multisrc:${{ github.event.inputs.lang }}:${{ github.event.inputs.extension }}:assembleDebug
          else
            ./gradlew :extensions:individual:${{ github.event.inputs.lang }}:${{ github.event.inputs.extension }}:assembleDebug
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.lang }}-${{ github.event.inputs.extension }}
          path: |
            src/${{ github.event.inputs.lang }}/${{ github.event.inputs.extension }}/build/outputs/apk/debug/*.apk,
            generated-src/${{ github.event.inputs.lang }}/${{ github.event.inputs.extension }}/build/outputs/apk/debug/*.apk
          retention-days: 1
